import fs from 'node:fs';
import path from 'node:path';

const corpusDir = path.resolve('src/features/flashcard/corpus');
const files = fs.readdirSync(corpusDir).filter(f => f.endsWith('.ts') && !f.includes('index') && !f.includes('test'));

const dictionary = {};

for (const file of files) {
  const content = fs.readFileSync(path.join(corpusDir, file), 'utf-8');
  // Match word: "..." and definition_vi: "..."
  const regex = /word:\s*["']([^"']+)["'][\s\S]*?definition_vi:\s*["']([^"']+)["']/g;
  let match;
  while ((match = regex.exec(content)) !== null) {
    const word = match[1].trim().toLowerCase();
    const definition = match[2].trim();
    if (!dictionary[word]) {
      dictionary[word] = definition;
    }
  }
}

const outDir = path.resolve('src/features/reading/data');
fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, 'dictionaryVi.json');
fs.writeFileSync(outPath, JSON.stringify(dictionary, null, 2), 'utf-8');

const tsPath = path.join(outDir, 'dictionaryVi.ts');
fs.writeFileSync(tsPath, `// Auto-generated by scripts/build_dictionary.mjs\nexport const DICTIONARY_VI: Record<string, string> = ${JSON.stringify(dictionary, null, 2)};\n`, 'utf-8');

console.log(`Successfully extracted ${Object.keys(dictionary).length} dictionary words to ${tsPath}`);

